Repository DiegoSHS/gpd_backend, pull requests merged in 2024-06, with the labels that each got.

#3 Add initial Prisma schema with relational model
  package-lock.json
  package.json
  prisma/migrations/20240623044222_db_init_migration/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: enhancement

#5 Add new dependency review workflow
  .github/workflows/dependency-review.yml
Labels: enhancement

#6 Authentication Implementation
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/codeql.yml
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20240623044222_db_init_migration/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/constants.ts
  src/auth/strategies/guards/jwt-auth.guard.ts
  src/auth/strategies/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/interceptors/bigint.interceptor.ts
  src/main.ts
  src/prisma.service.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: enhancement

#8 Integration of the Authentication branch to the dev branch
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/constants.ts
  src/auth/strategies/guards/jwt-auth.guard.ts
  src/auth/strategies/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/interceptors/bigint.interceptor.ts
  src/main.ts
  src/prisma.service.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: enhancement

#13 Implement CRUD operations for Template
  package-lock.json
  package.json
  prisma/migrations/migration_lock.toml
  src/app.module.ts
  src/models/template/create-template.dto.ts
  src/models/template/update-template.dto.ts
  src/templates/templates.controller.spec.ts
  src/templates/templates.controller.ts
  src/templates/templates.module.ts
  src/templates/templates.service.spec.ts
  src/templates/templates.service.ts
Labels: enhancement

#14 Added pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: documentation, enhancement

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#17 Create LICENSE
  LICENSE
Labels: documentation

#18 Fix: Remove Unique Constraint from areaId in Template Model
  prisma/migrations/20240630040535_remove_unique_constraint_from_area_id_from_the_template_table/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: bug
